### ISSUE TITLE
game.js - The end screen disks are unresponsive

### ISSUE THREAD

**Issue by NakerTheFirst** [sawolej/WaveProject#12]
**Versions**
`npm -v` 8.19.2
`tsc -v` 4.8.4
Terminal: Powershell 5.1.22000.832
Tested on branch: `feature-add-hightlight`

**What happened**
Self-explanatory

**Expected outcome**
The disks are responsive

**Comment by mikitfreek** [comment]
after collecting 13 discs, only 9 pics appear
